image: maxistar/arduino-esp32-ci

before_script:
  - 'command -v ssh-agent >/dev/null'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build:
  tags:
    - fomalgaut
  script:
    - echo "Building"
    - pushd firmware/sim7000
    - cp sim7000/config_prod.dist.h sim7000/config_prod.h
    - python -u /usr/src/app/compile.py
    - popd
deploy:
  tags:
    - fomalgaut
  rules:
    - when: manual
      allow_failure: true
  script:
    - echo "Deployment"
    - pushd firmware/sim7000
    - cp sim7000/config_prod.dist.h sim7000/config_prod.h
    - echo "$VERSION"
    - echo "$SERVER_URL"
    - python -u /usr/src/app/compile.py
    - scp sim7000_v1_0_0/sim7000.ino.bin "$SERVER_URL:/home/maxim/projects/fahrrad-tracker/server/web/firmware/$VERSION/smartbike.ino.esp32.bin"
    - popd

