image: maxistar/arduino-esp32-ci

build:
  tags:
    - fomalgaut
  script:
    - echo "Building"
    - pushd firmware/sim7000
    - cp sim7000/config_prod.dist.h sim7000/config_prod.h
    - python -u /usr/src/app/compile.py
    - popd
deploy:
  tags:
    - fomalgaut
  rules:
    - when: manual
      allow_failure: true
  script:
    - echo "Deployment"
    - pushd firmware/sim7000
    - cp sim7000/config_prod.dist.h sim7000/config_prod.h
    - echo $VERSION
    - popd

