image: maxistar/arduino-esp32-ci
stages:
  - build

build:
  stage: build
  tags:
    - fomalgaut

  script:
    - echo "Building"
    - cd firmware/sim7000
    - cp sim7000/config_prod.dist.h sim7000/config_prod.h
    - python -u /usr/src/app/compile.py
