version: '3.7'

networks:
  smartbike:

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: smartbike-app
    #restart: unless-stopped
    environment:
      - SOME_ENV=SOME_VALUE
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    networks:
      - smartbike
    command: "npm run dev"

  smartbike-db:
    image: mysql:5.7
    container_name: smartbike-db
    ports:
    - 3307:3306
    environment:
      MYSQL_DATABASE: mysql_server
      MYSQL_USER: smartbike
      MYSQL_PASSWORD: smartbike
      MYSQL_ROOT_PASSWORD: smartbike
    networks:
      - smartbike

  smartbike-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartbike-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    links:
      - smartbike-db
    ports:
      - 8090:80
    volumes:
      - /sessions
    networks:
      - smartbike

#;    networks:
#;    - smartbike
